### ISSUE TITLE
.terminal wider than #console

### ISSUE THREAD

**Issue by ajdlinux** [genuinetools/contained.af#11]
It looks like the div.terminal inside #console is wider than the #console.

In Chrome - http://imgur.com/a/AsQBb. It looks like the div#console is 1140x400, the div.terminal inside it is 1340x310

Less pronounced in Firefox: http://imgur.com/a/qCCQo - the div#console is 1140x400, the div.terminal is 1144x324.333.

Running Chrome 56.0.2924.87 and Firefox ESR 45.7.0 on Debian amd64.

If I have time this weekend I'll take a quick look at the CSS...

**Comment by jessfraz** [comment]
omg thank you, I am so bad at CSS I am very aware of the problem but fixing it is like playing with fire for me haha

**Comment by ajdlinux** [comment]
CSS, for when you get bored of kernel programming and want something more challenging and finicky

Taking a look at it now

**Comment by ajdlinux** [comment]
Replacing term.js with the much more maintained fork/successor http://xtermjs.org seems to help a lot here, also allows us to get other nice things like a scrollbar.

**Comment by jessfraz** [comment]
Oh nice!

**Comment by jessfraz** [comment]
it looks so much better! https://contained.af/
