### ISSUE TITLE
Trying to run contained.af locally on Linux Mint results in "Error response from daemon"

### ISSUE THREAD

**Issue by Winterflower** [genuinetools/contained.af#16]
**Full error message**
docker: Error response from daemon: cannot join network of a non running container: contained-dind.

**Steps to reproduce**
1. Clone contained.af repo
2. run ``make dev`` and ``make dind``. Successful. Run ``make run`` errors out with above error message. 
3.  Checked docker ps, contained-dind is not running. 

I should add, that I'm a total n00b so I'm going to duckduckgo a bit to see if I can make it work.

**Comment by jessfraz** [comment]
can you still reproduce this, let me know seems like the problem was that contained-dind was not running so you might want to check those logs
