### ISSUE TITLE
terminal output

### ISSUE THREAD

**Issue by pathcl** [genuinetools/contained.af#28]
So far Im trying to solve the game but at some point I cannot see the terminal any longer and start seeing these messages on chrome console.

<img width="1208" alt="screen shot 2018-08-18 at 00 22 48" src="https://user-images.githubusercontent.com/3768896/44291161-da7bf000-a27c-11e8-9511-6528b3af8763.png">

``
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at Object.proposeGeometry (contained.min.js:1)
    at Object.fit (contained.min.js:1)
    at g.e.fit (contained.min.js:1)
    at t (contained.min.js:1)
    at window.onresize (contained.min.js:1)
12contained.min.js:1 ``

**Comment by dezren39** [comment]
I have also experienced this. Differing times, hasn't happened while I've been actively typing, usually when clicking back after being on another tab. Chrome Version 70.0.3521.2 (Official Build) dev (64-bit)

**Comment by jessfraz** [comment]
If it's when you are unfocused for too long than that's a feature otherwise
I'd have a bunch of dangling containers but I guess I can increase the
timeout

**Comment by dezren39** [comment]
Makes sense. I suppose I could just not be slow too. I'll try and work on that.

**Comment by goshlanguage** [comment]
@pathcl seems that maybe this issue can be closed then? I experienced this but only over a really poor connection.
