### ISSUE TITLE
hints

### ISSUE THREAD

**Issue by jessfraz** [genuinetools/contained.af#4]
ping @marcosnils

right now hints are part of the "warning" https://github.com/jfrazelle/contained.af/blob/master/static/js/questions.js#L5 when they guess wrong but maybe we should have a tooltip or something.... I suck at javascript

**Comment by marcosnils** [comment]
@jfrazelle nice, that has been added recently right?
I was thinking about something a bit more powerful like different levels of hints like

```
"hints: ["try ping", "try man capabilities", "cat /proc/PID/tasks..."]
```

So each question might have different levels of hints that will help users to find the answer. 

I do have some stuff ready, I'll try crafting a PR soon.

**Comment by jessfraz** [comment]
ah it was always there you just might have gotten them all right :)

ah i like the different levels of hints like an ios game or something,
should we charge people to unlock, just kidding :)

but ya totally make a PR

On Tue, Jun 21, 2016 at 1:29 PM, Marcos Nils notifications@github.com
wrote:

> @jfrazelle https://github.com/jfrazelle nice, that has been added
> lately right?
> I was thinking about something a bit more powerful like different levels
> of hints like
> 
> "hints: ["try ping", "try man capabilities", "cat /proc/PID/tasks..."]
> 
> So each question might have different levels of hints that will help users
> to find the answer.
> 
> I do have some ready, I'll try crafting a PR soon.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/jfrazelle/contained.af/issues/4#issuecomment-227561760,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABYNbAlpZLfN-o6koGvVlXew0iG7nZX-ks5qOEmkgaJpZM4I7Iye
> .

## 

Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3

**Comment by marcosnils** [comment]
> should we charge people to unlock, just kidding :)

Watch out Fortune 500 here we come.

**Comment by bweston92** [comment]
:+1: I had to Google and research, makes me feel stupid I don't even know how to test `CAP_NET_RAW` aha.
